name: Phar

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Phar
      run: php -d "phar.readonly=0" generate.php
